# Generated by Django 3.1.3 on 2020-12-04 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamerraterapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='category_id',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='game',
            old_name='player_id',
            new_name='player',
        ),
    ]
