# Generated by Django 3.1.3 on 2020-12-04 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamerraterapi', '0002_auto_20201204_2235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='category',
            new_name='categories',
        ),
    ]
