# Generated by Django 3.1.3 on 2021-01-20 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamerraterapi', '0004_auto_20201205_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='num_of_players',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
